name: Restore PDM installation
inputs:
  pdm-version:
    description: "PDM version to install"
    required: true
    default: "2.18.1"
  uv-version:
    description: "uv version to install"
    required: true
    default: "0.4.6"

outputs:
  pdm-cache-dir:
    description: "PDM cache directory"
    value: ${{ steps.get-pdm-cache-path.outputs.pdm-cache-dir }}

runs:
  using: "composite"
  steps:
    - name: Get python version
      id: get-python-version
      uses: ./.github/actions/get-python-version
    - name: Install uv
      uses: astral-sh/setup-uv@v2
    - name: Get uv cache dir
      id: get-uv-cache-path
      shell: bash
      run: python .github/actions/restore-pdm/action.py uv
    - name: Restore PDM installation
      uses: actions/cache@v4
      with:
        path: ${{ steps.get-uv-cache-path.outputs.uv-cache-dir }}
        key: ${{ runner.os }}-python-${{ steps.get-python-version.outputs.python-version }}-pdm-${{ inputs.pdm-version }}
    - name: Install PDM
      shell: bash
      run: uv pip install pdm==${{ inputs.pdm-version }}
      env:
        UV_SYSTEM_PYTHON: 1
    - name: Get PDM cache dir
      id: get-pdm-cache-path
      shell: bash
      run: python .github/actions/restore-pdm/action.py pdm
