name: autofix.ci
on:
  pull_request:
    branches:
      - "main"
permissions: {}
jobs:
  lint:
    permissions:
      contents: read
    name: Code lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
      - name: Setup PDM
        uses: pdm-project/setup-pdm@544d7237314ee09c256785bd360f6b30add38b37 # v4.6
        with:
          python-version: "3.11"
          cache: true
      - name: Install deps
        run: pdm install --without benchmark
      - name: Restore prek hooks
        uses: actions/cache@v6.1.0
        with:
          path: ~/.cache/prek
          key: ${{ runner.os }}-prek-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Linter
        run: pdm lint
      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3.4
        if: always()
      - name: Type check
        run: pdm mypy
