name: Update dependencies
on:
  schedule:
    - cron: '0 0 * * 0'
jobs:
  dependencies-update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          persist-credentials: false
          ref: main
      - name: Setup PDM
        uses: pdm-project/setup-pdm@544d7237314ee09c256785bd360f6b30add38b37 # v4.6
        with:
          python-version: '3.11'
          cache: true
      - name: Update dependencies
        run: pdm update --update-all --unconstrained
      - name: Create Pull Request
        id: create-pr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          token: ${{ secrets.REPO_PAT }}
          branch: update/deps-autoupdate-${{ github.run_id }}
          title: Auto-update dependencies
          commit-message: Auto-update dependencies
      - name: Automerge commit
        if: ${{ steps.create-pr.outputs.pull-request-number }}
        run: gh pr merge "${PR_NUMBER}" --auto --squash --delete-branch
        env:
          GH_TOKEN: ${{ github.token }}
          PR_NUMBER: ${{ steps.create-pr.outputs.pull-request-number }}
